fixtures:
  repositories:
    "puppi": "https://github.com/example42/puppi.git"
    "monitor": "https://github.com/example42/puppet-monitor.git"
    "firewall": "https://github.com/example42/puppet-firewall.git"
    "iptables": "https://github.com/example42/puppet-iptables.git"
    "concat": "https://github.com/example42/puppet-concat.git"
    "stdlib": "https://github.com/example42/puppetlabs-stdlib.git"
    "mysql": "https://github.com/example42/puppet-mysql.git"
  symlinks:
    "pureftpd": "#{source_dir}"

